version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    networks:
      - be-net
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    networks:
      - be-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db:
    driver: local

networks:
  be-net:
    driver: bridge